name: Unit Test Unity
description: 'Runs unit test on a self-hosted runner'

runs:
  using: "composite"

  steps:
    - name: Grant Execute Permission for Unit Testing Script
      run: chmod +x ${{ github.action_path }}/test.sh
      shell: bash

    - name: Execute Unit Testing Script
      run: ${{ github.action_path }}/test.sh
      shell: bash
      env:
        TESTS_PATH: "test-results/results.xml"
