name: Unit Test Unity
description: 'Checks Unity for Compilation on a Build Target'
inputs:
  target-platform:
    description: Platform to Compile
    required: true

runs:
  using: "composite"

  steps:
    - name: Grant Execute Permission for Compiling Platform
      run: chmod +x ${{ github.action_path }}/compile.sh
      shell: bash

    - name: Compile a Platform
      run: ${{ github.action_path }}/compile.sh
      shell: bash
      env:
        TARGET: ${{ inputs.target-platform }}
