name: Activate Unity License
description: 'Activates the Unity License on the Self Hosted Runner'

runs:
  using: "composite"

  steps:
    - name: Grant Execute Permission for Activation Script
      run: chmod +x ${{ github.action_path }}/activate.sh
      shell: bash

    - name: Execute Activation Script
      run: ${{ github.action_path }}/activate.sh
      shell: bash
