name: Build IOS

on:
  schedule:
    # Scheduled to run Monday - Friday at 10:30AM UTC which is 3AM PST.
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 10 * * 1-5'
  workflow_dispatch:

env:
  UNITY_VERSION: 2021.3.28f1
  UNITY_VERSION_CHANGESET: 232e59c3f087
  UNITY_EXE_PATH: /Applications/Unity/Hub/Editor/2021.3.28f1/Unity.app/Contents/MacOS/Unity
  PROJECT_PATH: com.chartboost.mediation.canary
  BUILD_NAME: Builds/Canary
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  XCODE_VERSION_CANARY: "15"

# Cancels any queued or in-progress runs for this branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Chartboost Mediation Unity Canary IOS
    runs-on: m1

    steps:
    - name: "Set Build Path"
      run: |
        echo "BUILD_PATH=${{ env.PROJECT_PATH }}/${{ env.BUILD_NAME }}" >> $GITHUB_ENV

    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.GITHUBSERVICETOKEN }}
        lfs: true

    - name: Setup Unity Editor
      id: unity-install
      uses: ./chartboost-unity-ci/setup-unity
      timeout-minutes: 60
      with:
        unity-version: ${{ env.UNITY_VERSION }}
        unity-version-changeset: ${{ env.UNITY_VERSION_CHANGESET }}
        unity-modules:
          android
          ios

    - name: Activate Unity License
      id: activate-unity
      uses: ./chartboost-unity-ci/run-unity
      with:
        unity-executable-path: ${{ env.UNITY_EXE_PATH }}
        serial: ${{ secrets.UNITY_SERIAL }}
        username: ${{ secrets.UNITY_USERNAME }}
        password: ${{ secrets.UNITY_PASSWORD }}        

    - name: Build Chartboost Mediation Canary Unity IOS
      id: unity-android-build
      uses: ./chartboost-unity-ci/run-unity
      with:
        unity-executable-path: ${{ env.UNITY_EXE_PATH }}
        project-path: ${{ env.PROJECT_PATH }}
        target-platform: iOS
        execute-method: Editor.Builder.BuildIOS
        execute-method-args: | 
         -package_id com.chartboost.mediation 
         -build_name ${{ env.BUILD_NAME }} 
         -github_token ${{ secrets.GITHUBSERVICETOKEN }}
         -package_git_location https://${{ secrets.GITHUBSERVICETOKEN }}@github.com/ChartBoost/chartboost-mediation-unity-sdk-private.git?path=/com.chartboost.mediation

    - name: Return Unity License
      if: always()
      id: return-unity
      uses: ./chartboost-unity-ci/run-unity
      with:
        unity-executable-path: ${{ env.UNITY_EXE_PATH }}
        username: ${{ secrets.UNITY_USERNAME }}
        password: ${{ secrets.UNITY_PASSWORD }}
        return-license: true  

    # Setup the CI/CD environment
    - name: Setup IOS CI/CD environment
      id: ci-setup
      uses: ./chartboost-unity-ci/setup-environment-ios
      with:
        token: ${{ secrets.GITHUBSERVICETOKEN }}
        working-directory: ${{ env.BUILD_PATH }}

    # Update Cocoapods repositories to make sure we capture all the latest changes
    # before generating builds.
    # ⚠️ This step should only be performed when running on a self-hosted runner
    # due to how long this step takes and generally hosted runners will not need
    # this step since Github keeps their VMs up to date.
    - name: Update Cocoapods Repositories
      if: steps.ci-setup.outputs.is-local-runner
      timeout-minutes: 5
      run: pod repo update
      shell: bash
  
      # Update Cocoapods
    - name: Update Cocoapods
      if: steps.ci-setup.outputs.cocoapods-cached != 'true'
      run: pod install --project-directory=${{ env.BUILD_PATH }}
      shell: bash

    - name: Upload Canary Integration Changes
      continue-on-error: true
      run: |
        git config user.name ${{ secrets.GIT_USER }}
        git config user.email ${{ secrets.GIT_EMAIL }}
        git add ${{ env.PROJECT_PATH }}/Assets/Resources/5a4e797538a5f00cf60738d6.json
        git add ${{ env.PROJECT_PATH }}/Assets/Resources/5a4e797538a5f00cf60738d6.json.meta
        git add ${{ env.PROJECT_PATH }}/Assets/Resources/59c04299d989d60fc5d2c782.json
        git add ${{ env.PROJECT_PATH }}/Assets/Resources/59c04299d989d60fc5d2c782.json.meta
        git add ${{ env.PROJECT_PATH }}/Assets/com.chartboost.mediation/Editor/Adapters
        git add ${{ env.PROJECT_PATH }}/Assets/com.chartboost.mediation/Editor/ChartboostMediationDependencies.xml
        git add ${{ env.PROJECT_PATH }}/Assets/com.chartboost.mediation/Editor/selections.json
        git add ${{ env.PROJECT_PATH }}/Assets/Plugins/Android/mainTemplate.gradle
        git add ${{ env.PROJECT_PATH }}/ProjectSettings/AndroidResolverDependencies.xml
        git commit -m "Updating Canary Integration"
        git push --force

    - name: Set Build Type
      run: |
        # check if "adapter_updates.txt" file exists. This file is created only when adapters are updated
        if test -f adapter_updates.txt
        then 
          echo "adapters updated"
          echo "BUILD_TYPE=ADAPTER_CERTIFICATION" >> "$GITHUB_ENV"
        else
          echo "commit failed"
          if ${{ github.event_name == 'schedule' }}
          then
            echo "BUILD_TYPE=NIGHTLY_BUILD" >> "$GITHUB_ENV"
          else
            echo "BUILD_TYPE=AD_HOC" >> "$GITHUB_ENV"
          fi
        fi
        
    - name: Install Fastlane Dependencies
      run: bundle install
      shell: bash

    - name: Distribute Build
      run: bundle exec fastlane ios distribute
      shell: bash
      env:
        FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID }}
        FIREBASE_CI_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        BUILD_TYPE: ${{ env.BUILD_TYPE }}

    - name: Cleanup Unity Generated Files
      if: always()
      id: unity-cleanup
      uses: ./chartboost-unity-ci/cleanup-unity
      with:
        setup-pass: ${{ secrets.SETUP_PASS }}

    - name : Notify Slack on Failure
      if : ${{ failure() }}
      id : notify-slack
      uses: ./chartboost-unity-ci/notify-slack
      with:
        slack-webhook-url: ${{ secrets.SLACK_NOTIFY_CHARTBOOST_MEDIATION_UNITY_WEBHOOK }}
        workflow-run-id: ${{ github.run_id }}
        workflow-name: ${{ github.workflow }}
        workflow-url: "https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}"        
