name: ci-tests

on:
  # Trigger on pull requests that target the following branches
  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

# Cancels any queued or in-progress runs for this branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    # Always run on the latest MacOS version
    runs-on: [self-hosted]

    # Steps to perform for unit testing.
    steps:
    # Checkout the code
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Unity Editor
      id: unity-install
      uses:  ./.github/actions/setup-unity
      timeout-minutes: 60
      with:
        unity-version: 2020.3.15f2
        unity-version-changeset: 6cf78cb77498
        unity-modules:
          android
          ios
      env:
        SETUP_PASS: ${{ secrets.SETUP_PASS }}
