name: ci-tests

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.*'
  pull_request:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch:

# Cancels any queued or in-progress runs for this branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit Testing
    runs-on: [self-hosted]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Unity Editor
      id: unity-install
      uses:  ./.github/actions/setup-unity
      timeout-minutes: 60
      with:
        unity-version: 2020.3.27f1
        unity-version-changeset: e759542391ea
        unity-modules:
          android
          ios
      env:
        SETUP_PASS: ${{ secrets.SETUP_PASS }}

  compile:
    name: Compile Android Bridge
    runs-on: [self-hosted]
    needs: tests

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./com.chartboost.helium/Android~/gradlew

    - name: Build Android Bridge
      run: ./com.chartboost.helium/Android~/gradlew -p ./com.chartboost.helium/Android~ githubScript

    - name: Grant Execute Permission for Git Bridge Commit
      run: chmod +x ./.github/actions/uploadBridgeChanges.sh

    - name: Check for .jar Changes & Update
      run: ./.github/actions/uploadBridgeChanges.sh
