name: Helium Unity SDK

on:
  push:
    tags:
      - '3.*'
  pull_request:
    branches:
      - 'develop'
      - 'main'
  schedule:
    # Scheduled to run Monday - Friday at 9AM UTC which is 2AM PST.
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * 1-5'
  workflow_dispatch:
    inputs:
      helium_bridge_version:
        description: 'Helium Android Compile Version'
        required: false
        default: null
env:
  UNITY_VERSION: 2020.3.27f1
  UNITY_EXE_PATH: /Applications/Unity/Hub/Editor/2020.3.27f1/Unity.app/Contents/MacOS/Unity
  PROJECT_PATH: com.chartboost.helium.demo

# Cancels any queued or in-progress runs for this branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unity Actions & Unit Testing
    runs-on: [self-hosted]
    env:
      SETUP_PASS: ${{ secrets.SETUP_PASS }}
      UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Unity Editor
      id: unity-install
      uses: ./.github/actions/setup-unity
      timeout-minutes: 60
      with:
        unity-version: ${{ env.UNITY_VERSION }}
        unity-version-changeset: e759542391ea
        unity-modules:
          android
          ios

    - name: Activate Unity License
      id: activate-unity
      uses: ./.github/actions/activate-unity

    # Once we add mor platforms maybe we can run this in a matrix? this is fine for now.
    - name: Check for Compiler Errors in Standalone
      id: unity-compile-standalone
      uses: ./.github/actions/compile-unity
      with:
        target-platform: standalone

    - name: Check for Compiler Errors in Android
      id: unity-compile-android
      uses: ./.github/actions/compile-unity
      with:
        target-platform: android

    - name: Check for Compiler Errors in iOS
      id: unity-compile-ios
      uses: ./.github/actions/compile-unity
      with:
        target-platform: ios

    - name: Run Unity Unit Tests
      id: unity-unit-tests
      uses: ./.github/actions/test-unity

    - name: Cleanup Unity Generated Files
      id: unity-cleanup
      uses: ./.github/actions/cleanup-unity

    - name: Return Unity License
      if: always()
      id: return-unity
      uses: ./.github/actions/return-unity

  compile:
    name: Compile Android Bridge
    runs-on: [self-hosted]
    needs: tests

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set Up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./com.chartboost.helium/Android~/gradlew

    - name: Build Android Bridge
      run: ./com.chartboost.helium/Android~/gradlew -p ./com.chartboost.helium/Android~ githubScript
      env:
        HELIUM_VERSION: ${{ github.event.inputs.helium_bridge_version }}
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_PASS: ${{ secrets.JFROG_PASS }}

    - name: Grant Execute Permission for Git Bridge Commit
      run: chmod +x ./.github/actions/uploadBridgeChanges.sh

    - name: Check for Android Bridge .jar Changes & Update
      run: ./.github/actions/uploadBridgeChanges.sh
